[package]
name = "wist"
version = "0.1.0"
edition = "2024"
license = "ISC"
description = "Websocket Tunneling"

[dependencies]
itertools = { version = "0.14.0", default-features = false }
whisk = "0.13.0"
